### ISSUE TITLE
Warn when quitting app if there are pending blockchain operations

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_feedback#104]
Diode Drive should warn a user upon app close when there are still blockchain operations pending. 

<br>

**Current Behaviour:** 
1) User A invites User B to a Zone
2) User A closes Diode Drive before invite operation is complete
3) User B does not receive invite until User A comes back online and completes the invite operation

<br>

**Enhanced Behaviour:**
1) User A invites User B to a Zone
2) User A attempts to close Diode Drive
3) User A receives warning that invite operation is incomplete & that User B will not be invited if Diode Drive is closed 
4) User A chooses to exit app or wait for the pending invite operation to complete

**Comment by hansr** [comment]
@zach-pagel Do you think this is still an interesting improvement?

**Comment by zach-pagel** [comment]
I don't think so
