### ISSUE TITLE
Zone Names Not Kept Up-To-Date

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_feedback#105]
Software Details
--
![image](https://user-images.githubusercontent.com/17348062/127208663-08d5ad93-11ef-48fa-8686-bc0466bd79ac.png)
<br>
Description
--
**Problem:** Zone names (both in the global invite list and in already accepted Zones) are cached once upon invite receipt and never checked again. This is particularly problematic in the case of [Issue #106](https://github.com/diodechain/diode_drive_feedback/issues/106).
<br>
**Steps to Reproduce:**
1. User A invites User B to a Zone
2. User B receives invite, it doesn't matter if it is accepted or not (Zone name is saved by User B's client now)
3. User A changes Zone name
4. User B will not see the change that User A made to the Zone name anywhere in their client

**Comment by hansr** [comment]
Fixed
