### ISSUE TITLE
Invitee receives empty zone name if inviter is not online when invitee receives the invite

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_feedback#106]
Software Details
--
![image](https://user-images.githubusercontent.com/17348062/127208663-08d5ad93-11ef-48fa-8686-bc0466bd79ac.png)
Description
--
**Problem:** If user A invites User B to a Zone, and then goes offline before User B comes online, the invite that User B sees has an empty "name" field and User B will never see the name of the Zone - even if User A comes back online with User B.

**Steps to Reproduce:**
1. User A invites User B to a Zone
2. User A goes offline
3. User B comes online
4. User B receives the invite from User A, but with an empty name field
5. User A comes back online, but the name in the invite (or the accepted Zone, if the invite has been accepted) still does not populate for User B ([see Issue #105](https://github.com/diodechain/diode_drive_feedback/issues/105)).

<br>

**Screenshot**

- An invite that User B receives from User A while User A and User B are online together at the same time looks like this: Name (red) + Address (blue) 
- An invite that User B receives from User A while User A is offline looks like this: Address (blue)
<br>

![screenshot](https://user-images.githubusercontent.com/17348062/127212411-daaadcae-89a5-42e9-a52f-33ae31d2f942.png)

**Comment by zach-pagel** [comment]
I've noticed this same "blank name" issue occurring when a user is invited to a Zone before the Zone has finished posting it's existence to the chain.

**Comment by hansr** [comment]
Have not seen this issue for a while, closing for now.
