### ISSUE TITLE
File names ending with a backslash do not sync

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_feedback#114]
Software Details
--
The issue occurs at least on the following Linux platforms:
- Ubuntu 
- RaspberryOS 
- Andriod 

(Launcher Build: 1.2.1, Base Version: 1.2.1, Patch Level: v1.3.1)

Description
--
**Problem:** File names ending with "\\" do not sync.

**Steps to Reproduce:**
1. In a Zone shared between computer A and computer B, create files "test\\" and "test" using computer A.
2. Observe that computer B receives the file named "test," but never the file named "test\\" 
3. Create similar files from computer B and observe the same syncing pattern to computer A.

**Comment by dominicletz** [comment]
Nice one, we do support Windows for which `\` is not a valid filename character. So for now I think we will keep them unsupported and only support characters that all three platforms support. Let's reopen this when there is a use case coming up.
