### ISSUE TITLE
Video Link not embedding into MD file

### ISSUE THREAD

**Issue by Diodeeric** [diodechain/diode_feedback#136]
When inserting a video link into a MD file from YouTube, the MD file quickly shows a preview of the video but it disappears almost immediately.  Users are attempting to utilize the MD for notes or shared files with others and need the video to reference for their MD quick linked page.

**Comment by hansr** [comment]
We removed the ability to do this formally in 1.10.4.  The best way to do it now is to post an image of the video that is linked to an external site (like YouTube).
