### ISSUE TITLE
Ubuntu 18 requires installation of extra packages to load UI

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_feedback#14]
**Operating system and version:**
Linux Ubuntu 18

**dDrive version:**
0.7.2-8

**Problem description:**
Same user has verified dDrive works on Windows, but when installed on Ubuntu 18, "nothing happens".  Upon review of logs, dDrive is started, but the UI / icon is not visible.  Requires installation of https://extensions.gnome.org/extension/1031/topicons/.

After verifying icon loads, saw that file-syncs only work in one direction (from non-Ubuntu to Ubuntu, not when changed on Ubuntu) - this requires File Notify tools to be installed ("sudo apt install inotify-tools")

**Steps to reproduce:**
- Start with fresh Ubuntu 18 machine
- Install dDrive
- Run dDrive and note no UI loads
- Install https://extensions.gnome.org/extension/1031/topicons/ and verify UI now loads
- Add a file to the dDrive on the Ubuntu machine and note no file sync action is taken
- Install inotify-tools via terminal: sudo apt install inotify-tools
- Note now file changes/additions/deletions are now synchronized

**Comment by bluet** [comment]
I can confirm this.

And even with `topicons` extension, the tray location is still weird... 

![2020-12-15 06-50-13 的螢幕擷圖](https://user-images.githubusercontent.com/51141/102145243-d9394d00-3ea1-11eb-8c71-9916880b6391.png)

**Comment by dominicletz** [comment]
Better tray location with the other topicons extens: https://extensions.gnome.org/extension/495/topicons/

**Comment by dominicletz** [comment]
Also for proper functioning of the file monitoring the `inotify-tools` package with `inotifywait` is required at the moment
`sudo apt install inotify-tools`

**Comment by zach-pagel** [comment]
UI doesn't load on Ubuntu 20.04.1 LTS even after installing inotify-tools and the [TopIcons Plus gnome extension](https://extensions.gnome.org/extension/1031/topicons/).

**Comment by dominicletz** [comment]
> UI doesn't load on Ubuntu 20.04.1 LTS even after installing inotify-tools and the [TopIcons Plus gnome extension](https://extensions.gnome.org/extension/1031/topicons/).

Did you try both topicons extensions? https://extensions.gnome.org/extension/495/topicons/ ?

**Comment by zach-pagel** [comment]
> > UI doesn't load on Ubuntu 20.04.1 LTS even after installing inotify-tools and the [TopIcons Plus gnome extension](https://extensions.gnome.org/extension/1031/topicons/).
> 
> Did you try both topicons extensions? https://extensions.gnome.org/extension/495/topicons/ ?

I tried https://extensions.gnome.org/extension/495/topicons/, but it encounters an error when installing.

**Comment by zach-pagel** [comment]
[topiconsfix](https://extensions.gnome.org/extension/1674/topiconsfix) works with gnome 3.36.8 to access GUI

**Comment by hansr** [comment]
archlinux requires installation of openssl-1.0 

Before:
=ERROR REPORT==== 14-Apr-2021::20:53:47.116568 ===
Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library /home/chrisrempel/dDrive/lib/crypto-5.0/priv/lib/crypto: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.

**Comment by hansr** [comment]
Documented here: https://support.diode.io/article/j8e4a8a59a
