### ISSUE TITLE
Bug: Owner drops a drive but is immediately invited back to it by a peer

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_feedback#23]
**OS:** GNU/Linux 5.4.0-26-generic x86_64, Linux Mint 20 (this issue is also present on Windows 10)

**dDrive version:** 0.7.2 (patch version: v0.7.5-4-g9d4825b)

**Problem Description**:
The owner of a drive is immediately invited back to that drive by a peer after the owner drops the drive. 

**Steps to Reproduce:**
1. Create drive
2. Invite peer to drive
3. Peer accepts invite 
4. Owner drops drive from native manage drive window
5. Owner receives invite from peer to the drive dropped in step 4

**Comment by hansr** [comment]
Related to #28

**Comment by hansr** [comment]
Still exists in 1.0.1+9

**Comment by hansr** [comment]
There are additional issues here:
1) Create drive "A" from peer 1
2) Invite peer 2 and peer 3, allow them to sync
3) Using peer 1 (owner), remove peer 2, allow transaction to go through (e.g. transaction https://diode.io/prenet/#/tx/0x45502edb135fe0e55906c055cfee433443813b6e4bd2cc8635fb156cf3ea4fe4)
4) PROBLEM 1: peer 3 STILL SHOWS the peer 2 as a team member
5) PROBLEM 2: peer 2 STILL SHOWS the invite and allows re-acceptance.  Upon acceptance of the invite, it begins syncing from peer 3

@dominicletz

**Comment by hansr** [comment]
This is fixed
