### ISSUE TITLE
MacOS shrinks the task bar icon when connecting to an external monitor

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_feedback#67]
OS: All (using MacOS 10.15.4)

**Environment:** MacOS 10.15.4, Diode Drive 1.0.2-++

![image](https://user-images.githubusercontent.com/275153/112953775-54342400-9170-11eb-870d-4eddab4b3cd5.png)

**Problem Description:**
If I start / restart Diode Drive when my external monitor is connected, and I have the external monitor active, the Diode Drive icon in my task bar shrinks.

![image](https://user-images.githubusercontent.com/275153/112953905-78900080-9170-11eb-84a4-0f41073e0bdf.png)

**Expected Behavior:**
The Diode Drive icon should remain large:

<img width="95" alt="image" src="https://user-images.githubusercontent.com/275153/112953969-880f4980-9170-11eb-9061-e1dc3e41f5ff.png">

**Steps to Reproduce:**

1. Connect an external monitor  
2. While the external monitor is in focus, start Diode Drive
3. Observe the icon will be small

**Other Notes**
I think the issue "could be" that Mac is scaling the icon and trying to use the same scale on the task bars of both displays at the same time.  

I've tried debugging this by creating a number of icons of different sizes and replacing the icon in my /Applications/dDrive.app/Contents/Resources/lib/ddrive-1.0.1/priv folder.  However, no combination works (best is 16px multiples).  From the wxwidgets docs, it appears that perhaps it is possible to assign a .icns file as the icon that is used for the task bar icon - this may allow Mac to apply the right scale to the right display.

**Comment by dominicletz** [comment]
Fixed in 1.0.3, but need to install new build.

**Comment by hansr** [comment]
This is better now, although probably not perfect yet.  Closing for now.
