### ISSUE TITLE
Add explanation/instructions to tables with no data

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_feedback#82]
**UI Enhancement Description**
--
When launching Diode Drive for the first time, many of the pages that contain important information have yet to be filled. This can be confusing to the first-time user. When a page doesn't have any data to display, I suggest that a message be shown there and an action button provided to direct the user to the corresponding Diode Drive functionality.

**Examples**
--
**Zone Screen**
*Existing:*
![image](https://user-images.githubusercontent.com/17348062/118872973-cb538200-b8ae-11eb-90a0-95de1c09918e.png)
*Suggested:*
![image](https://user-images.githubusercontent.com/17348062/118872852-a7903c00-b8ae-11eb-9e77-88febf77c8db.png)

**Invite Screen**
*Existing:*
![image](https://user-images.githubusercontent.com/17348062/118873560-84b25780-b8af-11eb-9a87-8a872144b579.png)
*Suggested:*
![image](https://user-images.githubusercontent.com/17348062/118873449-66e4f280-b8af-11eb-8223-1a12cbdbd9bf.png)

**Files Screen**
*Existing:*
![image](https://user-images.githubusercontent.com/17348062/118874466-91837b00-b8b0-11eb-80ad-4110f7e71fdb.png)
*Suggested:*
![image](https://user-images.githubusercontent.com/17348062/118874371-71ec5280-b8b0-11eb-92db-7df72f870b84.png)

**Team Screen**
*Existing:*
![image](https://user-images.githubusercontent.com/17348062/118874622-bb3ca200-b8b0-11eb-85ba-5b21e3b98ea0.png)

*Suggested:*
![image](https://user-images.githubusercontent.com/17348062/118874786-e45d3280-b8b0-11eb-8367-a798cd19280a.png)

**Shares Screen**
*Existing:*
![image](https://user-images.githubusercontent.com/17348062/118875232-6a797900-b8b1-11eb-9b8b-bbc143749420.png)

*Suggested:*
![image](https://user-images.githubusercontent.com/17348062/118875143-4f0e6e00-b8b1-11eb-919b-de41da7737ba.png)

**Comment by hansr** [comment]
Great idea, will add to UX
